### ISSUE TITLE
Deleting from Database needs to happen "twice"

### ISSUE THREAD

**Issue by marsonfire** [marsonfire/ClubConnexions#1]
Whenever you delete something from the database, i.e. events, members, officers, etc. you need to refresh the page before it actually goes away. So, you essentially have to hit the "Delete ..." button twice in order to actually make the data disappear from the web page.

**Comment by schatzkara** [comment]
I changed this so that whenever it successfully deletes something from one of these pages, it automatically refreshes the page with the redirect() command
